import { useContext, useState, useEffect } from "react";
import Head from "next/head";

import NavBar from "./components/NavBar";
import ProductCard from "./components/ProductCard";

import modifyCart from "@/helpers/modifyCart";

import { CartContext } from "@/context/CartContext";

import { BASE_PRODUCT_URL } from "@/constants";

const Home = () => {
  const { cartProduct, setCartProduct } = useContext(CartContext);

  const [isLoading, setIsLoading] = useState(false);
  const [products, setProducts] = useState([]);

  const getProducts = async () => {
    setIsLoading(true);
    const res = await fetch(BASE_PRODUCT_URL);
    const data = await res.json();
    setProducts(data);
    setIsLoading(false);
  };

  useEffect(() => {
    getProducts();
  }, []);

  const handleAddToCart = (e, id) => {
    e.stopPropagation();
    const chosenProduct = products.find((product) => product.id === id);
    const modifiedCart = modifyCart(cartProduct, chosenProduct);
    setCartProduct(modifiedCart);
  };

  if (isLoading) {
    return (
      <div className="flex justify-center p-24 text-xl">Please wait..</div>
    );
  }
  return (
    <div className="flex flex-col lg:flex-row lg:h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>
        <div className="p-4 grid grid-cols-1 gap-2 md:grid-cols-3 md:gap-4 lg:grid-cols-4 xl:grid-cols-6">
          {products?.map((product) => {
            return (
              <div key={product.id}>
                <ProductCard
                  data={product}
                  onButtonClick={(e) => handleAddToCart(e, product.id)}
                />
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
};

export default Home;
